spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_authority_system?serverTimezone=UTC
    username: root
    password: Li123456
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    expire: 60000
  mvc:
    servlet:
      load-on-startup: 1
  main:
    banner-mode: off
request:
  login:
    url: /api/user/login
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.entity
  global-config:
    banner: false



