spring:
#  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_authority_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Li123456
#    redis服务器配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    expire: 60000
#    springmvc配置
  mvc:
    servlet:
      load-on-startup: 1
  main:
    banner-mode: off
#    前台请求路径
request:
  login:
    url: /api/user/login
#    mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.entity
  global-config:
    banner: false
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射 address_book ---> addressBook
    map-underscore-to-camel-case: true




